// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/item
//
// An item is a thing that your company buys, sells, or re-sells, such as products and services. An item is shown as a line on an invoice or other sales form.
package item
