// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/creditmemo
//
// The CreditMemo object is a financial transaction representing a refund or credit of payment or part of a payment for goods or services that have been sold.
package creditmemo
