// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/employee
//
// An Employee object represents a person working for the company.
//
// The DisplayName attribute must be unique.
// The GivenName, MiddleName, FamilyName, and PrintOnCheckName attributes must not contain a colon (:).
// The GivenName and FamilyName attributes are required.
// The PrimaryEmailAddress attribute must contain an at sign (@) and dot (.).
// The full complement of read, create, delete via deactivation (active=false), and update operations are available both with and without QuickBooks Payroll enabled. However, when Payroll is enabled, support for some attributes is limited:
// Title—Not supported when QuickBooks Payroll is enabled.
// Suffix—Not supported when QuickBooks Payroll is enabled.
// DisplayName —It’s read only when QuickBooks Payroll is enabled and a concatenation of GivenName MiddleName FamilyName.
// PrintOnCheckName—Not supported when QuickBooks Payroll is enabled.
// BillRate—Not supported when QuickBooks Payroll is enabled.
// SSN—Masked SSNs, as is returned in a response, cannot be passed in a request when QuickBooks Payroll is enabled. Code for this field must be removed before submitting.
package employee
