// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/paymentmethod
//
// The PaymentMethod resource provides the method of payment for received goods.
package paymentmethod
