// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/payment
//
// A Payment object records a payment in QuickBooks. The payment can be applied for a particular customer against multiple Invoices and Credit Memos. It can also be created without any Invoice or Credit Memo, by just specifying an amount.
package payment
