// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/taxcode
//
// A TaxCode object is used to track the taxable or non-taxable status of products, services, and customers. You can assign a sales tax code to each of your products, services, and customers based on their taxable or non-taxable status. You can then use these codes to generate reports that provide information to the tax agencies about the taxable or non-taxable status of certain sales.
package taxcode
