// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/bill
//
// A Bill object is an AP transaction representing a request-for-payment from a third party for goods/services rendered and/or received.
package bill
