// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/preferences
//
// The Preferences resource represents a set of company preferences that control application behavior in QuickBooks Online. They are mostly exposed as read-only through the Preferences endpoint with only a very small subset of them available as writable. Preferences are not necessarily honored when making requests via the QuickBooks API because a lot of them control UI behavior in the application and may not be applicable for apps.
//
// # Business Rules
//
// The create operation is not supported.
// The read request retrieves all preferences. There is no notion of preference objects or object IDs.
// Update operations are supported for a limited subset of preferences.
// The Delete operation is not supported.
// Query is supported with sorting and filtering enabled for Metadata timestamp attributes. Pagination is not supported.
// OtherPrefs type is used as an extension mechanism to contain additional attributes as Name/Value pairs.
package preferences
