// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/refundreceipt
//
// A RefundReceipt object represents a refund to the customer for a product or service that was provided.
package refundreceipt
