// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/class
//
// Class objects provide a way to track different segments of the business so they're not tied to a particular client or project. For example, you can define classes to break down the income and expenses for each business segment. Classes are available to the entire transaction or to individual detail lines of a transaction.
//
// Ref - https://developer.intuit.com/docs/0100_quickbooks_online/0200_dev_guides/accounting/class_tracking
package class
