// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/vendorcredit
//
// The VendorCredit object is an accounts payable transaction that represents a refund or credit of payment for goods or services. It is a credit that a vendor owes you for various reasons such as overpaid bill, returned merchandise, or other reasons.
package vendorcredit
