// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/department
//
// The Department resource provides a way to track transactions based on physical locations such as stores, sales regions, or countries. As you create sales and expense transactions, consistently designate the department to which they belong.
package department
