// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/purchase
//
// A Purchase object represents an expense, such as a purchase made from a vendor. There are three types of purchases: Cash, Check, and Credit Card.
//
// Cash Purchase contains information regarding a payment made in cash.
// Check Purchase contains information regarding a payment made by check.
// Credit Card Purchase contains information regarding a payment made by credit card or refunded/credited back to a credit card.
package purchase
