// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/transfer
//
// A Transfer represents a transaction where funds are moved between two accounts from the company's QuickBooks chart of accounts.
package transfer
