// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/companyinfo
//
// The CompanyInfo object contains basic company information. In QuickBooks, company info and preferences are displayed in the same place under preferences, so it may be confusing to figure out from user interface which fields may belong to this object. But in general, properties such as company addresses or name are considered company information. Some attributes may exist in both CompanyInfo and Preferences objects.
package companyinfo
