// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/taxagency
//
// A TaxAgency object is associated with a tax rate and identifies the agency to which that tax rate applies, that is, the entity that collects those taxes.
package taxagency
