// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/taxrate
//
// A TaxRate object represents rate applied to calculate tax liability. Use the TaxService entity to create a taxrate. See Global tax model for more information about using TaxRate objects and the tax model in general.
package taxrate
