// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/deposit
//
// A deposit object is a transaction that records one or more deposits of the following types:
//
// A customer payment, originally held in the Undeposited Funds account, into the Asset Account specified by the Deposit.DepositToAccountRef attribute. The Deposit.line.LinkedTxn element is used in this case to hold deposit information.
// A new, direct deposit specified by Deposit.Line.DepositLineDetail line detail.
package deposit
