// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/salesreceipt
//
// A SalesReceipt object represents the sales receipt that is given to a customer. A sales receipt is similar to an invoice. However, for a sales receipt, payment is received as part of the sale of goods and services. The sales receipt specifies a deposit account where the customer's payment is deposited. If the deposit account is not specified, the Undeposited Account is used.
package salesreceipt
