// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/timeactivity
//
// The TimeActivity object represents a record of time worked by a vendor or employee.
package timeactivity
