// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/purchaseorder
//
// The PurchaseOrder object is a non-posting transaction representing a request to purchase goods or services from a third party.
package purchaseorder
