// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/attachable
//
// This page covers the Attachable, Upload, and Download resources used for attachment management. Attachments are supplemental information linked to a transaction or Item object. They can be files, notes, or a combination of both.
//
// In the case of file attachments, use an upload endpoint multipart request to upload the files to the QuickBooks attachment list and, optionally, to supply metadata for each via an attachable object. If meta data is not supplied with the upload request, the system creates it.
// In the case of a note, use the create attachable endpoint.
// For information about attachments, see the Attachments Developer Guide.
package attachable
