// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/estimate
//
// Estimate represents a proposal for a financial transaction from a business to a customer for goods or services proposed to be sold, including proposed pricing.
package estimate
