// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/customer
//
// A customer is a consumer of the service or product that your business offers. The Customer object allows you to categorize customers according to your business requirements. To create a job, you must first create a customer and then create a job referencing that customer as a parent with the ParentRef attribute. Some areas a sub-customer/job can be used include:
//
// To track a job for the top-level customer, such as a kitchen remodel or bathroom remodel.
// Members of a team or league.
// Properties managed by a Homeowner Association or Property Management Company.
// See QuickBooks product documentation for more about sub-customers and jobs.
package customer
