// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/taxservice
//
// The TaxService resource allows you to perform the following actions:
//
// Create a new TaxCode object and specify a list of existing tax rates to be associated to that tax code. To retrieve a list of existing TaxCode objects, query the TaxCode resource.
// Create a new TaxRate object, dynamically. To retrieve a list of existing tax rates, query the TaxRate resource.
package taxservice
