// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/exchangerate
//
// Applicable only for those companies that enable multicurrency, the exchangerate resource provides the ability to query and set exchange rates available to the QuickBooks Online company. This entity works in combination with the companycurrency entity and the Currency Center in the QuickBooks Online UI to manage exchange rates for the company.
package exchangerate
