// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/invoice
//
// An Invoice represents a sales form where the customer pays for a product or service later.
package invoice
