// This file was auto-generated by Fern from our API Definition.

// https://developer.intuit.com/docs/api/accounting/journalentry
//
// JournalEntry is a transaction in which:
//
// There are at least one pair of lines, a debit and a credit, called distribution lines.
// Each distribution line has an account from the Chart of Accounts. Query the Account resource for a listing of the Chart of Accounts.
// The total of the debit column equals the total of the credit column.
// When you record a transaction with a JournalEntry object, the QuickBooks Online UI labels the transaction as JRNL in the register and as General Journal on reports that list transactions.
package journalentry
