// This file was auto-generated by Fern from our API Definition.

package api

type CdcReadRequest struct {
	Entities     *string `json:"-" url:"entities,omitempty"`
	ChangedSince *string `json:"-" url:"changedSince,omitempty"`
}
