// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
)

type CustomerCreateRequest struct {
	Operation *string   `json:"-" url:"operation,omitempty"`
	Body      *Customer `json:"-" url:"-"`
}

func (c *CustomerCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(Customer)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CustomerCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}
