// This file was auto-generated by Fern from our API Definition.

package api

type CustomerCreateRequest struct {
	Active    *bool   `json:"Active,omitempty" url:"-"`
	Id        *string `json:"Id,omitempty" url:"-"`
	SyncToken *string `json:"SyncToken,omitempty" url:"-"`
	Domain    *string `json:"domain,omitempty" url:"-"`
	Sparse    *bool   `json:"sparse,omitempty" url:"-"`
}
