// This file was auto-generated by Fern from our API Definition.

package api

type DepartmentCreateRequest struct {
	Active             *bool   `json:"Active,omitempty" url:"-"`
	FullyQualifiedName *string `json:"FullyQualifiedName,omitempty" url:"-"`
	Id                 *string `json:"Id,omitempty" url:"-"`
	Name               *string `json:"Name,omitempty" url:"-"`
	SubDepartment      *bool   `json:"SubDepartment,omitempty" url:"-"`
	SyncToken          *string `json:"SyncToken,omitempty" url:"-"`
	Domain             *string `json:"domain,omitempty" url:"-"`
	Sparse             *bool   `json:"sparse,omitempty" url:"-"`
}
