// This file was auto-generated by Fern from our API Definition.

package api

type EstimateCreateRequest struct {
	Operation *string `json:"-" url:"operation,omitempty"`
	Id        *string `json:"Id,omitempty" url:"-"`
	SyncToken *string `json:"SyncToken,omitempty" url:"-"`
}
