// This file was auto-generated by Fern from our API Definition.

package api

type ExchangerateGetdetailsRequest struct {
	Sourcecurrencycode *string `json:"-" url:"sourcecurrencycode,omitempty"`
	Asofdate           *string `json:"-" url:"asofdate,omitempty"`
	Minorversion       *string `json:"-" url:"minorversion,omitempty"`
}
