// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
)

type ItemCreateRequest struct {
	Minorversion *string `json:"-" url:"minorversion,omitempty"`
	Body         *Item   `json:"-" url:"-"`
}

func (i *ItemCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(Item)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.Body = body
	return nil
}

func (i *ItemCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}
