// This file was auto-generated by Fern from our API Definition.

package api

type JournalentryCreateRequest struct {
	Minorversion *string `json:"-" url:"minorversion,omitempty"`
	Operation    *string `json:"-" url:"operation,omitempty"`
	Id           *string `json:"Id,omitempty" url:"-"`
	SyncToken    *string `json:"SyncToken,omitempty" url:"-"`
}

type JournalentryReadbyidRequest struct {
	Minorversion *string `json:"-" url:"minorversion,omitempty"`
}
