// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/wepala/quickbooks-go/api/core"
)

type QueryReadRequest struct {
	Query *string `json:"-" url:"query,omitempty"`
}

type QueryReadResponse struct {
	QueryResponse *QueryResponse `json:"QueryResponse,omitempty" url:"QueryResponse,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (q *QueryReadResponse) GetExtraProperties() map[string]interface{} {
	return q.extraProperties
}

func (q *QueryReadResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler QueryReadResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QueryReadResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties

	q._rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryReadResponse) String() string {
	if len(q._rawJSON) > 0 {
		if value, err := core.StringifyJSON(q._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}
