// This file was auto-generated by Fern from our API Definition.

package api

type ReportAccountlistRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportAgedpayabledetailRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportAgedpayablesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportAgedreceivabledetailRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportAgedreceivablesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportBalancesheetRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCashflowRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCashsalesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCustomerbalanceRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCustomerbalancedetailRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCustomerincomeRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportCustomersalesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportDepartmentsalesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportGeneralledgerRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportInventoryvaluationsummaryRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportItemsalesRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportProfitandlossRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportProfitandlossdetailRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportTransactionlistRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportTrialbalanceRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportVendorbalanceRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportVendorbalancedetailRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}

type ReportVendorexpenseRequest struct {
	StartDate *string `json:"-" url:"start_date,omitempty"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
	Columns   *string `json:"-" url:"columns,omitempty"`
}
