// This file was auto-generated by Fern from our API Definition.

package api

type SalesreceiptCreateRequest struct {
	Operation *string `json:"-" url:"operation,omitempty"`
	Include   *string `json:"-" url:"include,omitempty"`
	Id        *string `json:"Id,omitempty" url:"-"`
	SyncToken *string `json:"SyncToken,omitempty" url:"-"`
	Sparse    *bool   `json:"sparse,omitempty" url:"-"`
}
