// This file was auto-generated by Fern from our API Definition.

package api

type TaxagencyCreateRequest struct {
	Minorversion *string `json:"-" url:"minorversion,omitempty"`
	DisplayName  *string `json:"DisplayName,omitempty" url:"-"`
}

type TaxagencyReadbyidRequest struct {
	Minorversion *string `json:"-" url:"minorversion,omitempty"`
}
