// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/wepala/quickbooks-go/api/core"
)

type TaxserviceCreateRequest struct {
	Minorversion   *string                                      `json:"-" url:"minorversion,omitempty"`
	TaxCode        *string                                      `json:"TaxCode,omitempty" url:"-"`
	TaxRateDetails []*TaxserviceCreateRequestTaxRateDetailsItem `json:"TaxRateDetails,omitempty" url:"-"`
}

type TaxserviceCreateRequestTaxRateDetailsItem struct {
	RateValue       *string `json:"RateValue,omitempty" url:"RateValue,omitempty"`
	TaxAgencyId     *string `json:"TaxAgencyId,omitempty" url:"TaxAgencyId,omitempty"`
	TaxApplicableOn *string `json:"TaxApplicableOn,omitempty" url:"TaxApplicableOn,omitempty"`
	TaxRateName     *string `json:"TaxRateName,omitempty" url:"TaxRateName,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TaxserviceCreateRequestTaxRateDetailsItem) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaxserviceCreateRequestTaxRateDetailsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler TaxserviceCreateRequestTaxRateDetailsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaxserviceCreateRequestTaxRateDetailsItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaxserviceCreateRequestTaxRateDetailsItem) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
