// This file was auto-generated by Fern from our API Definition.

package api

type TimeactivityCreateRequest struct {
	Id        *string `json:"Id,omitempty" url:"-"`
	SyncToken *string `json:"SyncToken,omitempty" url:"-"`
}
